#!/usr/bin/env node

/**
 * Google Play Store automation script
 * Generated by rn-launch-harness
 *
 * Usage:
 *   node scripts/publish.js --images                  # Metadata + image upload
 *   node scripts/publish.js --submit-only             # Review submission only
 *   node scripts/publish.js --images --submit         # Full: metadata + images + submit
 *   node scripts/publish.js --track internal          # Submit to specific track
 */

const { google } = require('googleapis');
const fs = require('fs');
const path = require('path');

// ── Config (auto-filled by harness) ──
const PACKAGE_NAME = '{{PACKAGE_NAME}}';
const KEY_FILE = path.resolve(__dirname, '..', process.env.GOOGLE_PLAY_SA_JSON || './credentials/google-play-sa.json');
const METADATA_DIR = path.resolve(__dirname, '..', 'docs/harness/store-assets/metadata');
const SCREENSHOTS_DIR = path.resolve(__dirname, '..', 'docs/harness/store-assets');

const APP_CONFIG = {
  contactEmail: '{{CONTACT_EMAIL}}',
  contactWebsite: '{{CONTACT_WEBSITE}}',
  contactPhone: '',
  defaultLanguage: 'ko-KR',
};

// ── CLI args ──
const args = process.argv.slice(2);
const submitOnly = args.includes('--submit-only');
const shouldSubmit = args.includes('--submit') || submitOnly;
const shouldUploadImages = args.includes('--images') && !submitOnly;
const shouldUpdateMeta = !submitOnly;
const trackIndex = args.indexOf('--track');
const track = trackIndex !== -1 ? args[trackIndex + 1] : 'production';

const IMAGE_FILES = {
  icon: { file: 'icon.png', type: 'icon' },
  featureGraphic: { file: 'feature_graphic.png', type: 'featureGraphic' },
};

async function main() {
  // ── 1. Auth ──
  if (!fs.existsSync(KEY_FILE)) {
    console.error('Service account key not found:', KEY_FILE);
    console.error('Set GOOGLE_PLAY_SA_JSON in .env or place the file at credentials/google-play-sa.json');
    process.exit(1);
  }

  const auth = new google.auth.GoogleAuth({
    keyFile: KEY_FILE,
    scopes: ['https://www.googleapis.com/auth/androidpublisher'],
  });

  const publisher = google.androidpublisher({ version: 'v3', auth });
  console.log('✓ Google Play API authenticated\n');

  // ── 2. Create Edit ──
  const { data: edit } = await publisher.edits.insert({
    packageName: PACKAGE_NAME,
  });
  const editId = edit.id;

  // Discover languages from metadata directory
  const languages = fs.existsSync(METADATA_DIR)
    ? fs.readdirSync(METADATA_DIR).filter((f) =>
        fs.statSync(path.join(METADATA_DIR, f)).isDirectory()
      )
    : ['ko-KR'];

  if (shouldUpdateMeta) {
    // ── 3. Store listings (title/description) ──
    for (const lang of languages) {
      const langDir = path.join(METADATA_DIR, lang);
      if (!fs.existsSync(langDir)) continue;

      const listing = {};
      const fields = {
        'title.txt': 'title',
        'short_description.txt': 'shortDescription',
        'full_description.txt': 'fullDescription',
      };

      for (const [file, key] of Object.entries(fields)) {
        const filePath = path.join(langDir, file);
        if (fs.existsSync(filePath)) {
          listing[key] = fs.readFileSync(filePath, 'utf8').trim();
        }
      }

      if (Object.keys(listing).length > 0) {
        await publisher.edits.listings.update({
          packageName: PACKAGE_NAME,
          editId,
          language: lang,
          requestBody: listing,
        });
        console.log(`✓ [${lang}] Store listing updated`);
      }
    }

    // ── 4. App details (contact info) ──
    try {
      await publisher.edits.details.update({
        packageName: PACKAGE_NAME,
        editId,
        requestBody: {
          contactEmail: APP_CONFIG.contactEmail,
          contactWebsite: APP_CONFIG.contactWebsite,
          defaultLanguage: APP_CONFIG.defaultLanguage,
        },
      });
      console.log('✓ Contact details updated');
    } catch (err) {
      console.log(`⚠ Details update failed: ${err.message}`);
    }
  }

  // ── 5. Image upload ──
  if (shouldUploadImages) {
    console.log('');

    // Icon & feature graphic
    for (const [label, { file, type }] of Object.entries(IMAGE_FILES)) {
      const filePath = path.join(SCREENSHOTS_DIR, file);
      if (fs.existsSync(filePath)) {
        try {
          await publisher.edits.images.deleteall({
            packageName: PACKAGE_NAME,
            editId,
            language: languages[0],
            imageType: type,
          });
        } catch (_) {}

        await publisher.edits.images.upload({
          packageName: PACKAGE_NAME,
          editId,
          language: languages[0],
          imageType: type,
          media: {
            mimeType: 'image/png',
            body: fs.createReadStream(filePath),
          },
        });
        console.log(`✓ ${label} uploaded: ${file}`);
      }
    }

    // Phone screenshots
    const screenshotDir = path.join(SCREENSHOTS_DIR, 'android', 'phone');
    if (fs.existsSync(screenshotDir)) {
      const phoneScreenshots = fs.readdirSync(screenshotDir)
        .filter((f) => /\.(png|jpg|jpeg)$/i.test(f))
        .sort();

      if (phoneScreenshots.length > 0) {
        for (const lang of languages) {
          try {
            await publisher.edits.images.deleteall({
              packageName: PACKAGE_NAME,
              editId,
              language: lang,
              imageType: 'phoneScreenshots',
            });
          } catch (_) {}

          for (const file of phoneScreenshots) {
            await publisher.edits.images.upload({
              packageName: PACKAGE_NAME,
              editId,
              language: lang,
              imageType: 'phoneScreenshots',
              media: {
                mimeType: 'image/png',
                body: fs.createReadStream(path.join(screenshotDir, file)),
              },
            });
            console.log(`✓ [${lang}] Screenshot uploaded: ${file}`);
          }
        }
      }
    }
  }

  // ── 6. Review submission ──
  if (shouldSubmit) {
    console.log('');

    const { data: trackData } = await publisher.edits.tracks.get({
      packageName: PACKAGE_NAME,
      editId,
      track,
    });

    if (trackData.releases && trackData.releases.length > 0) {
      const latestRelease = trackData.releases[0];
      const isDraft = latestRelease.status === 'draft';
      console.log(`Current [${track}]: v${latestRelease.versionCodes} (${latestRelease.status})`);

      try {
        await publisher.edits.tracks.update({
          packageName: PACKAGE_NAME,
          editId,
          track,
          requestBody: {
            track,
            releases: [
              {
                versionCodes: latestRelease.versionCodes,
                status: 'completed',
                releaseNotes: languages.map((lang) => ({
                  language: lang,
                  text: getReleaseNotes(lang),
                })),
              },
            ],
          },
        });
        console.log(`✓ [${track}] Submitted for review`);
      } catch (err) {
        if (isDraft) {
          // Draft apps cannot be set to 'completed' — update release notes only
          await publisher.edits.tracks.update({
            packageName: PACKAGE_NAME,
            editId,
            track,
            requestBody: {
              track,
              releases: [
                {
                  versionCodes: latestRelease.versionCodes,
                  status: 'draft',
                  releaseNotes: languages.map((lang) => ({
                    language: lang,
                    text: getReleaseNotes(lang),
                  })),
                },
              ],
            },
          });
          console.log(`✓ [${track}] Release notes updated (draft)`);
          console.log('');
          console.log('⚠ App is still in draft status.');
          console.log('  Complete these in Play Console before review submission:');
          console.log('  □ Content rating (IARC questionnaire)');
          console.log('  □ App category');
          console.log('  □ Countries/regions');
          console.log('  □ Data safety section');
        } else {
          throw err;
        }
      }
    } else {
      console.log(`⚠ [${track}] No releases found. Upload an AAB first.`);
    }
  }

  // ── 7. Commit edit ──
  await publisher.edits.commit({
    packageName: PACKAGE_NAME,
    editId,
  });

  console.log('\n✓ All changes applied!');

  // Manual items reminder
  console.log('\n─── Manual (API not supported) ───');
  console.log('  □ Content rating: IARC questionnaire (Play Console → App content → Content rating)');
  console.log('  □ App category: (Play Console → Store settings → App category)');
  console.log('  □ Countries: (Play Console → Production → Countries/regions)');
  console.log('  □ First AAB upload (app signing key registration, one-time only)');
}

function getReleaseNotes(lang) {
  const notesFile = path.join(METADATA_DIR, lang, 'release_notes.txt');
  if (fs.existsSync(notesFile)) {
    return fs.readFileSync(notesFile, 'utf8').trim();
  }
  return lang.startsWith('ko')
    ? '앱 출시'
    : 'App launch';
}

main().catch((err) => {
  console.error('\n✗ Error:', err.message);
  if (err.errors) {
    err.errors.forEach((e) => console.error('  -', e.message));
  }
  process.exit(1);
});
